cc_binary (
        name = 'show_server',
        srcs = 
                [
                        'server.cc',
                ],
        incs = 
                [
                ],
        deps = 
                [
                        '//third_party/curl:curl'
                ],
        extra_cppflags = 
                [
                        '-std=c++11',
                ],
)
