/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"https://github.com/whc10002/study.git\n"
"* master\n"
"commit c1c89a9e27b86bd5e33dcd32f0d1395ee2bf236f\n"
"Author: whc10002 <whc10002@sina.com>\n"
"Date:   Thu Apr 5 14:19:25 2018 +0000\n"
"\n"
"    add personnal projects\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Thu Apr  5 14:49:04 2018";
extern const char kBuilderName[] = "None";
extern const char kHostName[] = "PEKdev242.dev.fwmrm.net";
extern const char kCompiler[] = "GCC 4.8.3";
}}
